<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/src/type.proto

namespace GPBMetadata\Proto\Src;

class Type
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
{
proto/src/type.protocommon"%
Response
code (
msg (	""
Error
code (
msg (	BZcommonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

