<?php
# Generated by the protocol buffer compiler (hetao29/php-grpc-server-protobuf-plugin). DO NOT EDIT!
# source: src/info.proto

namespace User\Info;


interface InfoInterface
{
    // GRPC specific service name.
    public const NAME = "User.Info.Info";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param LoginRequest $in
    * @return LoginResponse
    *
    * @throws \Exception
    */
    public function login(LoginRequest $request): LoginResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param LogoutRequest $in
    * @return LogoutResponse
    *
    * @throws \Exception
    */
    public function logout(LogoutRequest $request): LogoutResponse;
}
