<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/info.proto

namespace User\Info;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>User.Info.LoginResponse</code>
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.common.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>.User.Info.UserInfo info = 2;</code>
     */
    protected $info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Common\Error $error
     *     @type \User\Info\UserInfo $info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Info::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.common.Error error = 1;</code>
     * @return \Common\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.common.Error error = 1;</code>
     * @param \Common\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Common\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.User.Info.UserInfo info = 2;</code>
     * @return \User\Info\UserInfo|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>.User.Info.UserInfo info = 2;</code>
     * @param \User\Info\UserInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \User\Info\UserInfo::class);
        $this->info = $var;

        return $this;
    }

}

