<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/info.proto

namespace User\Info;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>User.Info.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Uid = 1;</code>
     */
    protected $Uid = 0;
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Uid
     *     @type string $Name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Info::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->Uid;
    }

    /**
     * Generated from protobuf field <code>int64 Uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->Uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

}

